<?php

declare(strict_types=1);

namespace Gam6itko\OzonSeller\Service\V1;

use Gam6itko\OzonSeller\Service\AbstractService;
use Gam6itko\OzonSeller\TypeCaster;
use Gam6itko\OzonSeller\Utils\ArrayHelper;

/**
 * Types are derived from var/swagger.json.
 *
 * @psalm-type TMoney = array{currency_code?: string, value?: float}
 * @psalm-type TBalanceResponse = array{
 *     cashflows?: array{
 *         sales?: array{amount?: array, amount_details?: array, fee?: array},
 *         returns?: array{amount?: array, amount_details?: array, fee?: array},
 *         services?: list<array>
 *     },
 *     total?: array{
 *         opening_balance?: TMoney,
 *         closing_balance?: TMoney,
 *         accrued?: TMoney,
 *         payments?: list<array>
 *     }
 * }
 * @psalm-type TCashFlowStatementRequest = array{
 *     date: array{from: string, to: string},
 *     page?: int,
 *     page_size?: int,
 *     with_details?: bool
 * }
 * @psalm-type TCashFlowStatementResult = array{
 *     cash_flows?: list<array>,
 *     details?: array,
 *     page_count?: int
 * }
 * @psalm-type TAccrualType = array{id?: int, name?: string, description?: string}
 * @psalm-type TAccrual = array{
 *     accrual_id?: int,
 *     accrued_category?: 'UNSPECIFIED'|'POSTING'|'ITEM'|'NON_ITEM'|'CONTAINER_FEES',
 *     date?: string,
 *     unit_number?: string,
 *     posting?: array,
 *     item_fees?: array,
 *     non_item_fee?: array,
 *     container_fees?: array,
 *     total_amount?: array
 * }
 * @psalm-type TRealizationByDayResponse = array{
 *     rows?: list<array{
 *         rowNumber?: int,
 *         item?: array,
 *         commission_ratio?: float,
 *         delivery_commission?: array,
 *         return_commission?: array,
 *         seller_price_per_instance?: float
 *     }>
 * }
 * @psalm-type TRealizationPostingResponse = array{
 *     header?: array{
 *         number?: string,
 *         doc_date?: string,
 *         contract_date?: string,
 *         contract_number?: string,
 *         currency_sys_name?: string,
 *         payer_inn?: string,
 *         payer_kpp?: string,
 *         payer_name?: string,
 *         receiver_inn?: string,
 *         receiver_kpp?: string,
 *         receiver_name?: string,
 *         start_date?: string,
 *         stop_date?: string
 *     },
 *     rows?: list<array{
 *         row_number?: int,
 *         item?: array,
 *         order?: array,
 *         legal_entity_document?: array,
 *         commission_ratio?: float,
 *         delivery_commission?: array,
 *         return_commission?: array,
 *         seller_price_per_instance?: float
 *     }>
 * }
 * @psalm-type TDocumentCodeResult = array{code?: string}
 * @psalm-type TB2bSalesJsonResponse = array{
 *     date_from?: string,
 *     date_to?: string,
 *     seller_info?: array{company_name?: string, inn?: string, kpp?: string},
 *     invoices?: list<array{
 *         sku?: int,
 *         offer_id?: string,
 *         product_name?: string,
 *         currency?: string,
 *         currency_code?: int,
 *         unit_code?: int,
 *         unit_name?: string,
 *         buyer_info?: array,
 *         info?: array,
 *         operations?: list<array>
 *     }>
 * }
 * @psalm-type TProductsBuyoutResponse = array{
 *     products?: list<array{
 *         sku?: int,
 *         offer_id?: string,
 *         name?: string,
 *         posting_number?: string,
 *         quantity?: int,
 *         amount?: float,
 *         buyout_price?: float,
 *         seller_price_per_instance?: float,
 *         deduction_by_category_percent?: float,
 *         vat_percent?: int
 *     }>
 * }
 */
class FinanceService extends AbstractService
{
    private $path = '/v1/finance';

    /**
     * Returns a list of reports which were previously generated by Seller.
     *
     * @see https://docs.ozon.ru/api/seller/#tag/FinanceAPI
     *
     * @deprecated will be removed - use \Gam6itko\OzonSeller\Service\V2\FinanceService::realization
     *
     * @return array|string
     */
    public function realization(array $query)
    {
        $query = ArrayHelper::pick($query, ['date']);

        return $this->request('POST', "{$this->path}/realization", $query);
    }

    /**
     * Products realization report for a single day.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_CreateReportF3
     *
     * @return TRealizationByDayResponse
     */
    public function realizationByDay(int $year, int $month, int $day): array
    {
        return $this->request('POST', "{$this->path}/realization/by-day", [
            'year'  => $year,
            'month' => $month,
            'day'   => $day,
        ]);
    }

    /**
     * Per-order products realization report.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_CreateReportF4
     *
     * @return TRealizationPostingResponse
     */
    public function realizationPosting(int $year, int $month): array
    {
        return $this->request('POST', "{$this->path}/realization/posting", [
            'year'  => $year,
            'month' => $month,
        ]);
    }

    /**
     * Retrieves the balance report.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_GetBalance
     *
     * @return TBalanceResponse
     */
    public function balance(string $dateFrom, string $dateTo): array
    {
        return $this->request('POST', "{$this->path}/balance", [
            'date_from' => $dateFrom,
            'date_to'   => $dateTo,
        ]);
    }

    /**
     * Financial report.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_FinanceCashFlowStatementList
     *
     * @param TCashFlowStatementRequest $requestData
     *
     * @return TCashFlowStatementResult
     */
    public function cashFlowStatementList(array $requestData): array
    {
        $default = [
            'page'      => 1,
            'page_size' => 100,
        ];

        $requestData = array_merge(
            $default,
            ArrayHelper::pick($requestData, ['date', 'page', 'page_size', 'with_details'])
        );

        if (isset($requestData['date'])) {
            $requestData['date'] = ArrayHelper::pick($requestData['date'], ['from', 'to']);
        }

        $requestData = TypeCaster::castArr($requestData, [
            'page'         => 'int',
            'page_size'    => 'int',
            'with_details' => 'bool',
        ]);

        return $this->request('POST', "{$this->path}/cash-flow-statement/list", $requestData);
    }

    /**
     * Retrieves the accrual types dictionary.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_AccrualTypes
     *
     * @return array{accrual_types?: list<TAccrualType>}
     */
    public function accrualTypes(): array
    {
        return $this->request('POST', "{$this->path}/accrual/types", '{}');
    }

    /**
     * Retrieves accruals for a single day.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_AccrualByDay
     *
     * @param string $date   date in YYYY-MM-DD format
     * @param string $lastId last id from the previous response
     *
     * @return array{accruals?: list<TAccrual>, last_id?: string}
     */
    public function accrualByDay(string $date, string $lastId = ''): array
    {
        return $this->request('POST', "{$this->path}/accrual/by-day", [
            'date'    => $date,
            'last_id' => $lastId,
        ]);
    }

    /**
     * Retrieves accruals by postings.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_AccrualPostings
     *
     * @param list<string> $postingNumbers
     *
     * @return array{posting_accruals?: list<array{posting_number?: string, accruals?: list<array>}>}
     */
    public function accrualPostings(array $postingNumbers): array
    {
        return $this->request('POST', "{$this->path}/accrual/postings", [
            'posting_numbers' => array_map('strval', $postingNumbers),
        ]);
    }

    /**
     * B2B sales register. Returns a report code for /v1/report/info.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_DocumentB2BSales
     *
     * @param string $date     report month in YYYY-MM format
     * @param string $language DEFAULT|RU|EN
     *
     * @return TDocumentCodeResult
     */
    public function documentB2bSales(string $date, string $language = 'DEFAULT'): array
    {
        return $this->request('POST', "{$this->path}/document-b2b-sales", [
            'date'     => $date,
            'language' => $language,
        ]);
    }

    /**
     * B2B sales register in JSON format.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_DocumentB2BSalesJSON
     *
     * @param string $date report month in YYYY-MM format
     *
     * @return TB2bSalesJsonResponse
     */
    public function documentB2bSalesJson(string $date): array
    {
        return $this->request('POST', "{$this->path}/document-b2b-sales/json", ['date' => $date]);
    }

    /**
     * Mutual settlement report. Returns a report code for /v1/report/info.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_MutualSettlement
     *
     * @param string $date     report month in YYYY-MM format
     * @param string $language DEFAULT|RU|EN
     *
     * @return TDocumentCodeResult
     */
    public function mutualSettlement(string $date, string $language = 'DEFAULT'): array
    {
        return $this->request('POST', "{$this->path}/mutual-settlement", [
            'date'     => $date,
            'language' => $language,
        ]);
    }

    /**
     * Compensation report. Returns a report code for /v1/report/info.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_Compensation
     *
     * @param string $date     report month in YYYY-MM format
     * @param string $language DEFAULT|RU|EN
     *
     * @return TDocumentCodeResult
     */
    public function compensation(string $date, string $language = 'DEFAULT'): array
    {
        return $this->request('POST', "{$this->path}/compensation", [
            'date'     => $date,
            'language' => $language,
        ]);
    }

    /**
     * Decompensation report. Returns a report code for /v1/report/info.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_Decompensation
     *
     * @param string $date     report month in YYYY-MM format
     * @param string $language DEFAULT|RU|EN
     *
     * @return TDocumentCodeResult
     */
    public function decompensation(string $date, string $language = 'DEFAULT'): array
    {
        return $this->request('POST', "{$this->path}/decompensation", [
            'date'     => $date,
            'language' => $language,
        ]);
    }

    /**
     * Bought-out products report.
     *
     * @see https://docs.ozon.ru/api/seller/#operation/FinanceAPI_ProductsBuyout
     *
     * @return TProductsBuyoutResponse
     */
    public function productsBuyout(string $dateFrom, string $dateTo): array
    {
        return $this->request('POST', "{$this->path}/products/buyout", [
            'date_from' => $dateFrom,
            'date_to'   => $dateTo,
        ]);
    }
}
